services:
  ai-church-service-analyzer:
    build: .
    container_name: ai-church-service-analyzer
    environment:
      - DEEPGRAM_API_KEY=${DEEPGRAM_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - AUTHORIZATION_TOKEN=${AUTHORIZATION_TOKEN}
      - RECENT_AMOUNT=${RECENT_AMOUNT}
      - TRANSCRIPTION_SERVICE=${TRANSCRIPTION_SERVICE}
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - EMAIL_DOMAIN=${EMAIL_DOMAIN}
      - EMAIL_RECIPIENT=${EMAIL_RECIPIENT}
    volumes:
      - type: bind
        source: ./processed_services
        target: /app/processed_services
    restart: unless-stopped